[2024-07-18 22:02:32,204: INFO: main: Welcome to our custom logger!]
[2024-07-18 22:48:05,520: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-07-18 22:48:05,522: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-18 22:48:05,523: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-18 22:48:05,523: ERROR: main: yaml file is empty]
Traceback (most recent call last):
  File "/Users/sairoopesh/Documents/projects/KidneyDiseaseClassification/src/cnnClassifier/utils/common.py", line 32, in read_yaml
    return ConfigBox(content)
           ^^^^^^^^^^^^^^^^^^
  File "box/box.py", line 296, in box.box.Box.__init__
box.exceptions.BoxValueError: First argument must be mapping or iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sairoopesh/Documents/projects/KidneyDiseaseClassification/main.py", line 8, in <module>
    data_ingestion.main()
  File "/Users/sairoopesh/Documents/projects/KidneyDiseaseClassification/src/cnnClassifier/pipeline/stage_01_data_ingestion.py", line 14, in main
    config = ConfigurationManager()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sairoopesh/Documents/projects/KidneyDiseaseClassification/src/cnnClassifier/config/configuration.py", line 12, in __init__
    self.params = read_yaml(params_filepath)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/ensure/main.py", line 872, in __call__
    return_val = self.f(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sairoopesh/Documents/projects/KidneyDiseaseClassification/src/cnnClassifier/utils/common.py", line 34, in read_yaml
    raise ValueError("yaml file is empty")
ValueError: yaml file is empty
[2024-07-18 22:49:33,806: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-07-18 22:49:33,807: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-18 22:49:33,808: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-18 22:49:33,809: ERROR: main: yaml file is empty]
Traceback (most recent call last):
  File "/Users/sairoopesh/Documents/projects/KidneyDiseaseClassification/src/cnnClassifier/utils/common.py", line 32, in read_yaml
    return ConfigBox(content)
           ^^^^^^^^^^^^^^^^^^
  File "box/box.py", line 296, in box.box.Box.__init__
box.exceptions.BoxValueError: First argument must be mapping or iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sairoopesh/Documents/projects/KidneyDiseaseClassification/main.py", line 8, in <module>
    data_ingestion.main()
  File "/Users/sairoopesh/Documents/projects/KidneyDiseaseClassification/src/cnnClassifier/pipeline/stage_01_data_ingestion.py", line 13, in main
    config = ConfigurationManager()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sairoopesh/Documents/projects/KidneyDiseaseClassification/src/cnnClassifier/config/configuration.py", line 12, in __init__
    self.params = read_yaml(params_filepath)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/ensure/main.py", line 872, in __call__
    return_val = self.f(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sairoopesh/Documents/projects/KidneyDiseaseClassification/src/cnnClassifier/utils/common.py", line 34, in read_yaml
    raise ValueError("yaml file is empty")
ValueError: yaml file is empty
[2024-07-18 22:50:40,343: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-07-18 22:50:40,344: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-18 22:50:40,345: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-18 22:50:40,345: ERROR: main: yaml file is empty]
Traceback (most recent call last):
  File "/Users/sairoopesh/Documents/projects/KidneyDiseaseClassification/src/cnnClassifier/utils/common.py", line 32, in read_yaml
    return ConfigBox(content)
           ^^^^^^^^^^^^^^^^^^
  File "box/box.py", line 296, in box.box.Box.__init__
box.exceptions.BoxValueError: First argument must be mapping or iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sairoopesh/Documents/projects/KidneyDiseaseClassification/main.py", line 8, in <module>
    data_ingestion.main()
  File "/Users/sairoopesh/Documents/projects/KidneyDiseaseClassification/src/cnnClassifier/pipeline/stage_01_data_ingestion.py", line 13, in main
    config = ConfigurationManager()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sairoopesh/Documents/projects/KidneyDiseaseClassification/src/cnnClassifier/config/configuration.py", line 12, in __init__
    self.params = read_yaml(params_filepath)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/ensure/main.py", line 872, in __call__
    return_val = self.f(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sairoopesh/Documents/projects/KidneyDiseaseClassification/src/cnnClassifier/utils/common.py", line 34, in read_yaml
    raise ValueError("yaml file is empty")
ValueError: yaml file is empty
[2024-07-18 22:51:28,397: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-07-18 22:51:28,398: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-18 22:51:28,400: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-18 22:51:28,401: INFO: common: created directory at: artifacts]
[2024-07-18 22:51:28,401: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-18 22:51:28,401: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1CGBEGKaOaawXtvkI_C3cMwniKJGN-FLM/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-07-18 22:52:36,416: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1CGBEGKaOaawXtvkI_C3cMwniKJGN-FLM/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-07-18 22:52:41,901: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-07-18 23:15:44,870: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-07-18 23:15:47,503: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-07-18 23:15:47,504: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-18 23:15:47,506: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-18 23:15:47,506: INFO: common: created directory at: artifacts]
[2024-07-18 23:15:47,507: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-18 23:15:47,507: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1CGBEGKaOaawXtvkI_C3cMwniKJGN-FLM/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-07-18 23:16:56,721: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1CGBEGKaOaawXtvkI_C3cMwniKJGN-FLM/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-07-18 23:17:01,847: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-07-18 23:17:01,847: INFO: main: *******************]
[2024-07-18 23:17:01,847: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-07-18 23:17:01,848: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-18 23:17:01,849: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-18 23:17:01,849: INFO: common: created directory at: artifacts]
[2024-07-18 23:17:01,849: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-07-18 23:17:02,186: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-07-18 23:17:02,251: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-07-18 23:17:02,297: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-07-18 23:40:51,144: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-07-18 23:40:51,420: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-07-18 23:40:51,421: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-18 23:40:51,423: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-18 23:40:51,423: INFO: common: created directory at: artifacts]
[2024-07-18 23:40:51,423: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-18 23:40:51,423: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1CGBEGKaOaawXtvkI_C3cMwniKJGN-FLM/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-07-18 23:42:03,334: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1CGBEGKaOaawXtvkI_C3cMwniKJGN-FLM/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-07-18 23:42:09,168: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-07-18 23:42:09,168: INFO: main: *******************]
[2024-07-18 23:42:09,169: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-07-18 23:42:09,170: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-18 23:42:09,171: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-18 23:42:09,172: INFO: common: created directory at: artifacts]
[2024-07-18 23:42:09,173: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-07-18 23:42:09,504: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-07-18 23:42:09,570: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-07-18 23:42:09,613: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-07-18 23:42:09,613: INFO: main: *******************]
[2024-07-18 23:42:09,613: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-07-18 23:42:09,613: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-18 23:42:09,614: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-18 23:42:09,614: INFO: common: created directory at: artifacts]
[2024-07-18 23:42:09,614: INFO: common: created directory at: artifacts/training]
[2024-07-18 23:42:09,681: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-07-18 23:42:10,432: ERROR: main: Unknown variable: <KerasVariable shape=(25088, 2), dtype=float32, path=dense/kernel>. This optimizer can only be called for the variables it was originally built with. When working with a new set of variables, you should recreate a new optimizer instance.]
Traceback (most recent call last):
  File "/Users/sairoopesh/Documents/projects/KidneyDiseaseClassification/main.py", line 32, in <module>
    model_trainer.main()
  File "/Users/sairoopesh/Documents/projects/KidneyDiseaseClassification/src/cnnClassifier/pipeline/stage_03_model_training.py", line 18, in main
    training.train()
  File "/Users/sairoopesh/Documents/projects/KidneyDiseaseClassification/src/cnnClassifier/components/model_training.py", line 68, in train
    self.model.fit(
  File "/opt/anaconda3/lib/python3.12/site-packages/keras/src/utils/traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/opt/anaconda3/lib/python3.12/site-packages/keras/src/optimizers/base_optimizer.py", line 228, in _check_variables_are_known
    raise ValueError(
ValueError: Unknown variable: <KerasVariable shape=(25088, 2), dtype=float32, path=dense/kernel>. This optimizer can only be called for the variables it was originally built with. When working with a new set of variables, you should recreate a new optimizer instance.
[2024-07-18 23:44:17,612: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-07-18 23:44:17,826: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-07-18 23:44:17,827: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-18 23:44:17,830: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-18 23:44:17,830: INFO: common: created directory at: artifacts]
[2024-07-18 23:44:17,830: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-18 23:44:17,830: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1CGBEGKaOaawXtvkI_C3cMwniKJGN-FLM/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-07-18 23:45:25,592: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1CGBEGKaOaawXtvkI_C3cMwniKJGN-FLM/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-07-18 23:45:31,669: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-07-18 23:45:31,670: INFO: main: *******************]
[2024-07-18 23:45:31,670: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-07-18 23:45:31,671: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-18 23:45:31,673: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-18 23:45:31,674: INFO: common: created directory at: artifacts]
[2024-07-18 23:45:31,674: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-07-18 23:45:32,016: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-07-18 23:45:32,109: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-07-18 23:45:32,168: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-07-18 23:45:32,168: INFO: main: *******************]
[2024-07-18 23:45:32,168: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-07-18 23:45:32,169: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-18 23:45:32,169: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-18 23:45:32,169: INFO: common: created directory at: artifacts]
[2024-07-18 23:45:32,169: INFO: common: created directory at: artifacts/training]
[2024-07-18 23:45:32,240: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-07-18 23:45:32,990: ERROR: main: Unknown variable: <KerasVariable shape=(25088, 2), dtype=float32, path=dense/kernel>. This optimizer can only be called for the variables it was originally built with. When working with a new set of variables, you should recreate a new optimizer instance.]
Traceback (most recent call last):
  File "/Users/sairoopesh/Documents/projects/KidneyDiseaseClassification/main.py", line 32, in <module>
    model_trainer.main()
  File "/Users/sairoopesh/Documents/projects/KidneyDiseaseClassification/src/cnnClassifier/pipeline/stage_03_model_training.py", line 18, in main
    training.train()
  File "/Users/sairoopesh/Documents/projects/KidneyDiseaseClassification/src/cnnClassifier/components/model_training.py", line 71, in train
    self.model.fit(
  File "/opt/anaconda3/lib/python3.12/site-packages/keras/src/utils/traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/opt/anaconda3/lib/python3.12/site-packages/keras/src/optimizers/base_optimizer.py", line 228, in _check_variables_are_known
    raise ValueError(
ValueError: Unknown variable: <KerasVariable shape=(25088, 2), dtype=float32, path=dense/kernel>. This optimizer can only be called for the variables it was originally built with. When working with a new set of variables, you should recreate a new optimizer instance.
[2024-07-18 23:53:20,283: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-07-18 23:53:20,484: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-07-18 23:53:20,485: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-18 23:53:20,487: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-18 23:53:20,487: INFO: common: created directory at: artifacts]
[2024-07-18 23:53:20,487: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-18 23:53:20,487: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1CGBEGKaOaawXtvkI_C3cMwniKJGN-FLM/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-07-18 23:54:29,135: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1CGBEGKaOaawXtvkI_C3cMwniKJGN-FLM/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-07-18 23:54:35,016: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-07-18 23:54:35,017: INFO: main: *******************]
[2024-07-18 23:54:35,017: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-07-18 23:54:35,018: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-18 23:54:35,019: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-18 23:54:35,020: INFO: common: created directory at: artifacts]
[2024-07-18 23:54:35,020: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-07-18 23:54:35,288: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-07-18 23:54:35,369: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-07-18 23:54:35,424: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-07-18 23:54:35,424: INFO: main: *******************]
[2024-07-18 23:54:35,424: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-07-18 23:54:35,425: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-18 23:54:35,425: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-18 23:54:35,425: INFO: common: created directory at: artifacts]
[2024-07-18 23:54:35,426: INFO: common: created directory at: artifacts/training]
[2024-07-18 23:54:35,494: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-07-18 23:54:36,135: ERROR: main: Unknown variable: <KerasVariable shape=(25088, 2), dtype=float32, path=dense/kernel>. This optimizer can only be called for the variables it was originally built with. When working with a new set of variables, you should recreate a new optimizer instance.]
Traceback (most recent call last):
  File "/Users/sairoopesh/Documents/projects/KidneyDiseaseClassification/main.py", line 32, in <module>
    model_trainer.main()
  File "/Users/sairoopesh/Documents/projects/KidneyDiseaseClassification/src/cnnClassifier/pipeline/stage_03_model_training.py", line 18, in main
    training.train()
  File "/Users/sairoopesh/Documents/projects/KidneyDiseaseClassification/src/cnnClassifier/components/model_training.py", line 69, in train
    self.model.fit(
  File "/opt/anaconda3/lib/python3.12/site-packages/keras/src/utils/traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/opt/anaconda3/lib/python3.12/site-packages/keras/src/optimizers/base_optimizer.py", line 228, in _check_variables_are_known
    raise ValueError(
ValueError: Unknown variable: <KerasVariable shape=(25088, 2), dtype=float32, path=dense/kernel>. This optimizer can only be called for the variables it was originally built with. When working with a new set of variables, you should recreate a new optimizer instance.
[2024-07-19 00:04:25,223: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-07-19 00:04:25,481: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-07-19 00:04:25,482: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-19 00:04:25,483: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-19 00:04:25,484: INFO: common: created directory at: artifacts]
[2024-07-19 00:04:25,484: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-19 00:04:25,484: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1CGBEGKaOaawXtvkI_C3cMwniKJGN-FLM/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-07-19 00:05:34,786: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1CGBEGKaOaawXtvkI_C3cMwniKJGN-FLM/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-07-19 00:05:40,453: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-07-19 00:05:40,453: INFO: main: *******************]
[2024-07-19 00:05:40,453: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-07-19 00:05:40,454: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-19 00:05:40,456: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-19 00:05:40,457: INFO: common: created directory at: artifacts]
[2024-07-19 00:05:40,457: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-07-19 00:05:40,786: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-07-19 00:05:40,859: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-07-19 00:05:40,924: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-07-19 00:05:40,924: INFO: main: *******************]
[2024-07-19 00:05:40,924: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-07-19 00:05:40,925: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-19 00:05:40,926: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-19 00:05:40,926: INFO: common: created directory at: artifacts]
[2024-07-19 00:05:40,926: INFO: common: created directory at: artifacts/training]
[2024-07-19 00:05:40,995: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-07-19 00:05:41,754: ERROR: main: Unknown variable: <KerasVariable shape=(25088, 2), dtype=float32, path=dense/kernel>. This optimizer can only be called for the variables it was originally built with. When working with a new set of variables, you should recreate a new optimizer instance.]
Traceback (most recent call last):
  File "/Users/sairoopesh/Documents/projects/KidneyDiseaseClassification/main.py", line 32, in <module>
    model_trainer.main()
  File "/Users/sairoopesh/Documents/projects/KidneyDiseaseClassification/src/cnnClassifier/pipeline/stage_03_model_training.py", line 18, in main
    training.train()
  File "/Users/sairoopesh/Documents/projects/KidneyDiseaseClassification/src/cnnClassifier/components/model_training.py", line 71, in train
    self.model.fit(
  File "/opt/anaconda3/lib/python3.12/site-packages/keras/src/utils/traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/opt/anaconda3/lib/python3.12/site-packages/keras/src/optimizers/base_optimizer.py", line 228, in _check_variables_are_known
    raise ValueError(
ValueError: Unknown variable: <KerasVariable shape=(25088, 2), dtype=float32, path=dense/kernel>. This optimizer can only be called for the variables it was originally built with. When working with a new set of variables, you should recreate a new optimizer instance.
[2024-07-19 00:16:09,128: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-07-19 00:16:09,388: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-07-19 00:16:09,389: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-19 00:16:09,391: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-19 00:16:09,391: INFO: common: created directory at: artifacts]
[2024-07-19 00:16:09,391: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-19 00:16:09,391: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1CGBEGKaOaawXtvkI_C3cMwniKJGN-FLM/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-07-19 00:17:19,607: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1CGBEGKaOaawXtvkI_C3cMwniKJGN-FLM/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-07-19 00:17:25,352: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-07-19 00:17:25,352: INFO: main: *******************]
[2024-07-19 00:17:25,352: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-07-19 00:17:25,353: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-19 00:17:25,355: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-19 00:17:25,356: INFO: common: created directory at: artifacts]
[2024-07-19 00:17:25,356: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-07-19 00:17:25,674: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-07-19 00:17:25,735: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-07-19 00:17:25,784: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-07-19 00:17:25,784: INFO: main: *******************]
[2024-07-19 00:17:25,784: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-07-19 00:17:25,785: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-19 00:17:25,785: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-19 00:17:25,785: INFO: common: created directory at: artifacts]
[2024-07-19 00:17:25,785: INFO: common: created directory at: artifacts/training]
[2024-07-19 00:17:25,857: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-07-19 13:28:44,355: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-07-19 13:28:44,692: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-07-19 13:28:44,694: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-19 13:28:44,696: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-19 13:28:44,696: INFO: common: created directory at: artifacts]
[2024-07-19 13:28:44,696: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-19 13:28:44,696: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1CGBEGKaOaawXtvkI_C3cMwniKJGN-FLM/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-07-19 13:29:55,405: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1CGBEGKaOaawXtvkI_C3cMwniKJGN-FLM/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-07-19 13:30:02,034: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-07-19 13:30:02,034: INFO: main: *******************]
[2024-07-19 13:30:02,034: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-07-19 13:30:02,036: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-19 13:30:02,039: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-19 13:30:02,040: INFO: common: created directory at: artifacts]
[2024-07-19 13:30:02,040: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-07-19 13:30:02,408: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-07-19 13:30:02,488: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-07-19 13:30:02,556: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-07-19 13:30:02,557: INFO: main: *******************]
[2024-07-19 13:30:02,557: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-07-19 13:30:02,558: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-19 13:30:02,559: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-19 13:30:02,559: INFO: common: created directory at: artifacts]
[2024-07-19 13:30:02,559: INFO: common: created directory at: artifacts/training]
[2024-07-19 13:30:02,633: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-07-19 14:09:27,541: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-07-19 14:09:28,061: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-07-19 17:28:10,978: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-07-19 17:28:10,981: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-19 17:28:10,982: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-19 17:28:10,982: INFO: common: created directory at: artifacts]
[2024-07-19 17:28:10,982: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-19 17:28:10,982: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1CGBEGKaOaawXtvkI_C3cMwniKJGN-FLM/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-07-19 17:29:19,428: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1CGBEGKaOaawXtvkI_C3cMwniKJGN-FLM/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-07-19 17:29:24,471: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-07-19 17:29:24,472: INFO: main: *******************]
[2024-07-19 17:29:24,472: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-07-19 17:29:24,473: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-19 17:29:24,474: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-19 17:29:24,474: INFO: common: created directory at: artifacts]
[2024-07-19 17:29:24,475: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-07-19 17:29:24,796: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-07-19 17:29:24,876: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-07-19 17:29:24,932: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-07-19 17:29:24,932: INFO: main: *******************]
[2024-07-19 17:29:24,932: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-07-19 17:29:24,933: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-19 17:29:24,934: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-19 17:29:24,934: INFO: common: created directory at: artifacts]
[2024-07-19 17:29:24,934: INFO: common: created directory at: artifacts/training]
[2024-07-19 17:29:24,994: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-07-19 18:07:17,660: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-07-19 18:07:18,002: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-07-19 18:07:18,003: INFO: main: *******************]
[2024-07-19 18:07:18,003: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-07-19 18:07:18,010: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-19 18:07:18,013: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-19 18:07:18,014: INFO: common: created directory at: artifacts]
[2024-07-19 18:07:18,098: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-07-19 18:10:01,028: INFO: common: json file saved at: scores.json]
[2024-07-19 18:10:01,029: INFO: common: json file saved at: scores.json]
[2024-07-19 18:10:01,029: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-07-19 22:28:18,722: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-07-19 22:28:18,725: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-19 22:28:18,726: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-19 22:28:18,726: INFO: common: created directory at: artifacts]
[2024-07-19 22:28:18,726: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-19 22:28:18,726: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1CGBEGKaOaawXtvkI_C3cMwniKJGN-FLM/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-07-19 22:29:27,159: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1CGBEGKaOaawXtvkI_C3cMwniKJGN-FLM/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-07-19 22:29:32,952: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-07-19 22:29:32,952: INFO: main: *******************]
[2024-07-19 22:29:32,952: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-07-19 22:29:32,954: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-19 22:29:32,955: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-19 22:29:32,955: INFO: common: created directory at: artifacts]
[2024-07-19 22:29:32,955: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-07-19 22:29:33,283: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-07-19 22:29:33,370: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-07-19 22:29:33,428: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-07-19 22:29:33,428: INFO: main: *******************]
[2024-07-19 22:29:33,428: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-07-19 22:29:33,429: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-19 22:29:33,429: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-19 22:29:33,429: INFO: common: created directory at: artifacts]
[2024-07-19 22:29:33,429: INFO: common: created directory at: artifacts/training]
[2024-07-19 22:29:33,494: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-07-19 23:13:14,759: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-07-19 23:13:15,054: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-07-19 23:13:15,055: INFO: main: *******************]
[2024-07-19 23:13:15,055: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-07-19 23:13:15,066: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-19 23:13:15,070: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-19 23:13:15,071: INFO: common: created directory at: artifacts]
[2024-07-19 23:13:15,196: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-07-19 23:16:45,458: INFO: common: json file saved at: scores.json]
[2024-07-19 23:16:45,459: INFO: common: json file saved at: scores.json]
[2024-07-19 23:16:45,771: ERROR: main: Invalid filepath extension for saving. Please add either a `.keras` extension for the native Keras format (recommended) or a `.h5` extension. Use `model.export(filepath)` if you want to export a SavedModel for use with TFLite/TFServing/etc. Received: filepath=/var/folders/46/08x7cxl11vgcvv8g60pz4jr40000gn/T/tmp1w96jpo4/model/data/model.]
Traceback (most recent call last):
  File "/Users/sairoopesh/Documents/projects/KidneyDiseaseClassification/main.py", line 44, in <module>
    model_evalution.main()
  File "/Users/sairoopesh/Documents/projects/KidneyDiseaseClassification/src/cnnClassifier/pipeline/stage_04_model_evaluation.py", line 18, in main
    evaluation.log_into_mlflow()
  File "/Users/sairoopesh/Documents/projects/KidneyDiseaseClassification/src/cnnClassifier/components/model_evaluation_mlflow.py", line 72, in log_into_mlflow
    mlflow.keras.log_model(self.model, "model")
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/mlflow/tensorflow/__init__.py", line 222, in log_model
    return Model.log(
           ^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/mlflow/models/model.py", line 551, in log
    flavor.save_model(path=local_path, mlflow_model=mlflow_model, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/mlflow/tensorflow/__init__.py", line 437, in save_model
    model.save(model_path, **keras_model_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/keras/src/saving/saving_api.py", line 106, in save_model
    raise ValueError(
ValueError: Invalid filepath extension for saving. Please add either a `.keras` extension for the native Keras format (recommended) or a `.h5` extension. Use `model.export(filepath)` if you want to export a SavedModel for use with TFLite/TFServing/etc. Received: filepath=/var/folders/46/08x7cxl11vgcvv8g60pz4jr40000gn/T/tmp1w96jpo4/model/data/model.
[2024-07-19 23:25:13,956: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-07-19 23:25:13,958: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-19 23:25:13,959: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-19 23:25:13,959: INFO: common: created directory at: artifacts]
[2024-07-19 23:25:13,959: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-19 23:25:13,959: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1CGBEGKaOaawXtvkI_C3cMwniKJGN-FLM/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-07-19 23:26:22,886: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1CGBEGKaOaawXtvkI_C3cMwniKJGN-FLM/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-07-19 23:26:27,510: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-07-19 23:26:27,511: INFO: main: *******************]
[2024-07-19 23:26:27,511: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-07-19 23:26:27,512: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-19 23:26:27,513: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-19 23:26:27,513: INFO: common: created directory at: artifacts]
[2024-07-19 23:26:27,513: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-07-19 23:26:27,848: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-07-19 23:26:27,924: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-07-19 23:26:27,980: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-07-19 23:26:27,980: INFO: main: *******************]
[2024-07-19 23:26:27,980: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-07-19 23:26:27,981: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-19 23:26:27,982: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-19 23:26:27,982: INFO: common: created directory at: artifacts]
[2024-07-19 23:26:27,982: INFO: common: created directory at: artifacts/training]
[2024-07-19 23:26:28,043: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-07-20 00:08:41,825: WARNING: saving_api: The `save_format` argument is deprecated in Keras 3. We recommend removing this argument as it can be inferred from the file path. Received: save_format=h5]
[2024-07-20 00:08:41,832: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-07-20 00:08:42,101: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-07-20 00:08:42,102: INFO: main: *******************]
[2024-07-20 00:08:42,102: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-07-20 00:08:42,117: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-20 00:08:42,122: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-20 00:08:42,124: INFO: common: created directory at: artifacts]
[2024-07-20 00:08:42,234: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-07-20 00:11:41,492: INFO: common: json file saved at: scores.json]
[2024-07-20 00:11:41,494: INFO: common: json file saved at: scores.json]
[2024-07-20 00:11:41,750: ERROR: main: log_model() got an unexpected keyword argument 'save_format']
Traceback (most recent call last):
  File "/Users/sairoopesh/Documents/projects/KidneyDiseaseClassification/main.py", line 44, in <module>
    model_evalution.main()
  File "/Users/sairoopesh/Documents/projects/KidneyDiseaseClassification/src/cnnClassifier/pipeline/stage_04_model_evaluation.py", line 18, in main
    evaluation.log_into_mlflow()
  File "/Users/sairoopesh/Documents/projects/KidneyDiseaseClassification/src/cnnClassifier/components/model_evaluation_mlflow.py", line 72, in log_into_mlflow
    mlflow.keras.log_model(self.model, "model",  save_format="h5")
TypeError: log_model() got an unexpected keyword argument 'save_format'
[2024-07-20 08:58:26,096: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-07-20 08:58:26,100: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-20 08:58:26,101: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-20 08:58:26,102: INFO: common: created directory at: artifacts]
[2024-07-20 08:58:26,102: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-20 08:58:26,102: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1CGBEGKaOaawXtvkI_C3cMwniKJGN-FLM/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-07-20 08:59:36,437: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1CGBEGKaOaawXtvkI_C3cMwniKJGN-FLM/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-07-20 08:59:42,580: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-07-20 08:59:42,581: INFO: main: *******************]
[2024-07-20 08:59:42,581: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-07-20 08:59:42,583: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-20 08:59:42,584: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-20 08:59:42,584: INFO: common: created directory at: artifacts]
[2024-07-20 08:59:42,584: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-07-20 08:59:43,041: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-07-20 08:59:43,142: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-07-20 08:59:43,227: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-07-20 08:59:43,227: INFO: main: *******************]
[2024-07-20 08:59:43,227: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-07-20 08:59:43,229: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-20 08:59:43,230: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-20 08:59:43,230: INFO: common: created directory at: artifacts]
[2024-07-20 08:59:43,230: INFO: common: created directory at: artifacts/training]
[2024-07-20 08:59:43,336: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-07-20 10:29:05,043: WARNING: saving_api: The `save_format` argument is deprecated in Keras 3. We recommend removing this argument as it can be inferred from the file path. Received: save_format=h5]
[2024-07-20 10:29:05,045: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-07-20 10:29:05,404: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-07-20 10:29:05,405: INFO: main: *******************]
[2024-07-20 10:29:05,405: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-07-20 10:29:05,412: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-20 10:29:05,416: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-20 10:29:05,418: INFO: common: created directory at: artifacts]
[2024-07-20 10:29:05,527: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-07-20 10:33:29,302: INFO: common: json file saved at: scores.json]
[2024-07-20 10:33:29,304: INFO: common: json file saved at: scores.json]
[2024-07-20 10:33:29,304: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
