[2024-07-18 22:02:32,204: INFO: main: Welcome to our custom logger!]
[2024-07-18 22:48:05,520: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-07-18 22:48:05,522: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-18 22:48:05,523: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-18 22:48:05,523: ERROR: main: yaml file is empty]
Traceback (most recent call last):
  File "/Users/sairoopesh/Documents/projects/KidneyDiseaseClassification/src/cnnClassifier/utils/common.py", line 32, in read_yaml
    return ConfigBox(content)
           ^^^^^^^^^^^^^^^^^^
  File "box/box.py", line 296, in box.box.Box.__init__
box.exceptions.BoxValueError: First argument must be mapping or iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sairoopesh/Documents/projects/KidneyDiseaseClassification/main.py", line 8, in <module>
    data_ingestion.main()
  File "/Users/sairoopesh/Documents/projects/KidneyDiseaseClassification/src/cnnClassifier/pipeline/stage_01_data_ingestion.py", line 14, in main
    config = ConfigurationManager()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sairoopesh/Documents/projects/KidneyDiseaseClassification/src/cnnClassifier/config/configuration.py", line 12, in __init__
    self.params = read_yaml(params_filepath)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/ensure/main.py", line 872, in __call__
    return_val = self.f(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sairoopesh/Documents/projects/KidneyDiseaseClassification/src/cnnClassifier/utils/common.py", line 34, in read_yaml
    raise ValueError("yaml file is empty")
ValueError: yaml file is empty
[2024-07-18 22:49:33,806: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-07-18 22:49:33,807: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-18 22:49:33,808: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-18 22:49:33,809: ERROR: main: yaml file is empty]
Traceback (most recent call last):
  File "/Users/sairoopesh/Documents/projects/KidneyDiseaseClassification/src/cnnClassifier/utils/common.py", line 32, in read_yaml
    return ConfigBox(content)
           ^^^^^^^^^^^^^^^^^^
  File "box/box.py", line 296, in box.box.Box.__init__
box.exceptions.BoxValueError: First argument must be mapping or iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sairoopesh/Documents/projects/KidneyDiseaseClassification/main.py", line 8, in <module>
    data_ingestion.main()
  File "/Users/sairoopesh/Documents/projects/KidneyDiseaseClassification/src/cnnClassifier/pipeline/stage_01_data_ingestion.py", line 13, in main
    config = ConfigurationManager()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sairoopesh/Documents/projects/KidneyDiseaseClassification/src/cnnClassifier/config/configuration.py", line 12, in __init__
    self.params = read_yaml(params_filepath)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/ensure/main.py", line 872, in __call__
    return_val = self.f(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sairoopesh/Documents/projects/KidneyDiseaseClassification/src/cnnClassifier/utils/common.py", line 34, in read_yaml
    raise ValueError("yaml file is empty")
ValueError: yaml file is empty
[2024-07-18 22:50:40,343: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-07-18 22:50:40,344: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-18 22:50:40,345: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-18 22:50:40,345: ERROR: main: yaml file is empty]
Traceback (most recent call last):
  File "/Users/sairoopesh/Documents/projects/KidneyDiseaseClassification/src/cnnClassifier/utils/common.py", line 32, in read_yaml
    return ConfigBox(content)
           ^^^^^^^^^^^^^^^^^^
  File "box/box.py", line 296, in box.box.Box.__init__
box.exceptions.BoxValueError: First argument must be mapping or iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sairoopesh/Documents/projects/KidneyDiseaseClassification/main.py", line 8, in <module>
    data_ingestion.main()
  File "/Users/sairoopesh/Documents/projects/KidneyDiseaseClassification/src/cnnClassifier/pipeline/stage_01_data_ingestion.py", line 13, in main
    config = ConfigurationManager()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sairoopesh/Documents/projects/KidneyDiseaseClassification/src/cnnClassifier/config/configuration.py", line 12, in __init__
    self.params = read_yaml(params_filepath)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/ensure/main.py", line 872, in __call__
    return_val = self.f(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sairoopesh/Documents/projects/KidneyDiseaseClassification/src/cnnClassifier/utils/common.py", line 34, in read_yaml
    raise ValueError("yaml file is empty")
ValueError: yaml file is empty
[2024-07-18 22:51:28,397: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-07-18 22:51:28,398: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-07-18 22:51:28,400: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-18 22:51:28,401: INFO: common: created directory at: artifacts]
[2024-07-18 22:51:28,401: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-18 22:51:28,401: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1CGBEGKaOaawXtvkI_C3cMwniKJGN-FLM/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-07-18 22:52:36,416: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1CGBEGKaOaawXtvkI_C3cMwniKJGN-FLM/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-07-18 22:52:41,901: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
